# Generated by Django 2.2 on 2020-12-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201224_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/0.jpg', upload_to='avatar/%Y%m%d'),
        ),
    ]
